data:
  class_path: data.cmr2025.CMR2025DataModule
  init_args:
    data_path: ./h5_dataset_simplified
    train_path: ./h5_dataset_simplified/train
    val_path: ./h5_dataset_simplified/val
    sample_rate: 0.5
    volume_sample_rate: 1.0
    train_accelerations: [4, 8, 12]
    val_accelerations: [4, 8, 12]
    crop_size: [320, 190]  # Make sure width is <= 198
    batch_size: 4
    num_workers: 8
    use_seed: true
    pad_sides: false
    fix_acceleration_val: 8