data:
  class_path: pl_modules.DataModule
  init_args:
    slice_dataset: data.FastmriSliceDataset
    data_path: /gpfs/home/bingyx01/mridatasets/fm-brain
    challenge: multicoil
    train_transform:
      class_path: data.FastmriDataTransform
      init_args:
        mask_func:
          class_path: data.RandomMaskFunc
          init_args:
            center_fractions:
            - 0.08 
            - 0.04
            accelerations:
            - 4
            - 8
            allow_any_combination: false
        uniform_resolution:
        - 384
        - 384
        use_seed: false
    val_transform:
      class_path: data.FastmriDataTransform
      init_args:
        mask_func:
          class_path: data.RandomMaskFunc
          init_args:
            center_fractions:
            - 0.08 
            - 0.04
            accelerations:
            - 4
            - 8
            allow_any_combination: false
        uniform_resolution:
        - 384
        - 384
        use_seed: true
    combine_train_val: true
    num_adj_slices: &n_adj_slc 3
    batch_size: 1
    distributed_sampler: true
    use_dataset_cache_file: false

# dataset specific settings
trainer:
  devices: 2
  num_nodes: 1
  max_epochs: 45
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: exp/fm-brain/pmr # path to save experiment and checkpoint 
      tags: [fastmri-brain]
      name: fm-brain-pmr

model:
  class_path: pl_modules.PromptMrModule
  init_args:
    lr: 0.0001
    lr_step_size: 35
    num_adj_slices: *n_adj_slc
    sens_n_feat0: 12
    sens_feature_dim: [18, 24, 30]
    sens_prompt_dim: [6, 12, 18]
    no_use_ca: true

ckpt_path: null

